# Generated by Django 4.2.10 on 2025-06-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_ride_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='dropoff_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='dropoff_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='pickup_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='pickup_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
