# Generated by Django 4.2.10 on 2025-07-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_ride_dropoff_lat_ride_dropoff_lng_ride_pickup_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
    ]
