# Generated by Django 4.2.10 on 2025-07-25 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0006_sharedride_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedrideinvite',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='rides.sharedride'),
        ),
        migrations.DeleteModel(
            name='SharedRideRequest',
        ),
    ]
